# Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
data = pd.read_csv('cleaned_dataset.csv')
data.head()

/tmp/ipykernel_365124/3513733778.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('cleaned_dataset.csv')

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Free,Price,Currency,...,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 55,Unnamed: 56
0,Logistics Management,com.eniseistudio.logistics_management,Education,4.090909,66.0,10000.0,10000.0,True,0.0,USD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Estados Unidos Noticias,com.eniseistudio.news.estados_unidos,News & Magazines,4.000000,8.0,1000.0,1000.0,True,0.0,USD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dental Assistant,com.eniseistudio.dental_assistant,Education,3.866667,15.0,10000.0,10000.0,True,0.0,USD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Medical Assistant,com.eniseistudio.course.medical_assistant,Education,4.000000,18.0,5000.0,5000.0,True,0.0,USD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Business Administration,com.eniseistudio.majors.course.business_admini...,Education,4.023256,86.0,50000.0,50000.0,True,0.0,USD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Feature Selection and Encoding

In [3]:
# Selecting relevant features for classification
features = data[['Rating', 'Rating Count', 'Installs', 'Size', 'Free', 'Category']]

features = features.dropna()

# Binarize the 'Rating' feature to create a classification problem (e.g., high-rated vs low-rated)
# Let's assume a rating of 4.0 and above is high-rated (1) and below 4.0 is low-rated (0)
features['High_Rated'] = (features['Rating'] >= 4.0).astype(int)

# Drop the original 'Rating' column
features = features.drop('Rating', axis=1)

# One-hot encoding the 'Category' column
features = pd.get_dummies(features, columns=['Category'])

# Splitting the features and target variable
X = features.drop('High_Rated', axis=1)
y = features['High_Rated']

# Scaling the numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Model Training and Evaluation

## Naive Bayes

In [4]:
# Train a Naive Bayes classifier
nb = GaussianNB()
nb.fit(X_train, y_train)

# Make predictions
y_pred_nb = nb.predict(X_test)

# Evaluate the model
print("Naive Bayes Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))

Naive Bayes Classifier
Accuracy: 0.565126670734828
              precision    recall  f1-score   support

           0       0.54      0.64      0.59     24595
           1       0.59      0.49      0.54     26206

    accuracy                           0.57     50801
   macro avg       0.57      0.57      0.56     50801
weighted avg       0.57      0.57      0.56     50801

[[15762  8833]
 [13259 12947]]

In [5]:
# Train a Random Forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Make predictions
y_pred_rf = rf.predict(X_test)

# Evaluate the model
print("Random Forest Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Classifier
Accuracy: 0.7499852365110923
              precision    recall  f1-score   support

           0       0.76      0.71      0.73     24595
           1       0.74      0.79      0.77     26206

    accuracy                           0.75     50801
   macro avg       0.75      0.75      0.75     50801
weighted avg       0.75      0.75      0.75     50801

[[17414  7181]
 [ 5520 20686]]

In [ ]:
# Train a Support Vector Machine classifier
svm = SVC(kernel='linear', random_state=42)
svm.fit(X_train, y_train)

# Make predictions
y_pred_svm = svm.predict(X_test)

# Evaluate the model
print("Support Vector Machine Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))